# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: correar
      MYSQL_PASSWORD: rodrigoc
      MYSQL_ROOT_PASSWORD: rodricoc2
      MYSQL_DATABASE: Prueba2


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80